### ISSUE TITLE
Missing dependency in viatra-query-language

### ISSUE THREAD

**Issue by kkadosa** [eclipse-viatra/org.eclipse.viatra#169]
The dependency `org.eclipse.emf.codegen.ecore` is missing from the viatra-query-language, making it inoperable.

The dependency contains the `GenModel` package, which is required by the `EMFPatternLanguageRuntimeModule` (through `MetamodelProviderService`, `BaseMetamodelProviderService`, `EcoreGenmodelRegistry`).

**Comment by ujhelyiz** [comment]
I have merged the related pr to the 2.8-maintenance branch and cherry-picked it over the master branch as well. I think this ticket can now be closed.
