### ISSUE TITLE
Can't build Viatra projects with VQL queries in 2024-09

### ISSUE THREAD

**Issue by adisandro** [eclipse-viatra/org.eclipse.viatra#191]
Errors running builder 'Xtext Project Builder' on project XXX
because of
java.lang.NoClassDefFoundError: org/eclipse/pde/internal/core/natures/PDE

This class has been removed in the PDE plugin:
https://github.com/eclipse-pde/eclipse.pde/commit/a37e0a10d8e3c3fbeb3805e5f7cf8391dc04855c#diff-3db8ee6e94ccc7c2d6e13b52ef2caa0b8025e9ed4640a7b3bfefa55656f5e412

But Viatra still uses it, e.g. here:
[org.eclipse.viatra.query.tooling.core.project.ProjectGenerationHelper.isOpenPDEProject(ProjectGenerationHelper.java:118)](https://github.com/eclipse-viatra/org.eclipse.viatra/blob/de0513829a240c4b1ae06998de2f21ff71a4c6fd/query/plugins/org.eclipse.viatra.query.tooling.core/src/org/eclipse/viatra/query/tooling/core/project/ProjectGenerationHelper.java#L118C57-L118C60)

See this discussion with some different ways to fix it:
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/578

Could you issue a fix for the 2024-09 stream?

**Comment by ujhelyiz** [comment]
Thanks for noticing this, it is strange that we have missed this.

We will provide a fix ASAP (hopefully during next week).

**Comment by ujhelyiz** [comment]
Fixed in both 2.9-maintenance and master branches.
